server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/studentsDb
    username: root
    password: Root2324
  jpa:
    hibernate:
      ddl-auto: create
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka